### PR TITLE
Add transaction queue management

### PR DESCRIPTION
**Pull request by cdjackson**
This is the initial addition of a transaction queue layer, following on from the transaction manager that was added in #479. It provides a queuing mechanism to better manager the link between applications and the dongle. It currently supports the following features -:

* Retry of failed transactions
* Ensures a minimum spacing between each message sent to a specific address
* Enforces a maximum number of outstanding messages to any address

Transactions are send to the ```ZigBeeNetworkManager``` using the same API as is currently implemented.

The diagram below shows the general flow from the application sending a transaction to the
```ZigBeeTransactionManager```, into the ```ZigBeeTransactionQueue```, and the interaction with the ```ZigBeeTransportTransmit``` and ```ZigBeeTransportRecieve``` classes.

image
 
The```ZigBeeTransactionManager``` manages the overall transaction process. It acts as the central configuration interface for configuring the transaction subsystem, and handles sending and receiving of commands. It gets transactions from the different queues, selecting a queue randomly, and enforces an overall maximum number of transactions that can be outstanding. Of the outstanding transactions, it will only allow a specific number to be sent to sleepy nodes at once to avoid delaying commands being sent to powered nodes (since sleepy nodes may take some time to respond).

The ```ZigBeeTransactionQueue``` handles the transactions for a single queue. A queue is established for each node, along with broadcasts and multicast message queues. The ```ZigBeeTransactionQueue``` enforces the maximum number of outstanding messages for this queue, and ensures a minimum delay between each subsequent transaction release. The ```ZigBeeTransactionQueue``` is notified of all completed transactions so it can add failed transactions back in the queue if retries are required.

The ```ZigBeeTransactionProfile``` is used to configure the queues.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 045758ce5e4fa4a1bf6ec854743bb43dbd220694 into 62de467e231c2d41fc1eca1b13d9737b3dac66c8 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-517aebf6649eddc9e6ce6a77cc7c6168420e04bd)

**new alerts:**

* 1 for Spurious Javadoc @param tags
* 1 for Unused format argument

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 1 alert** when merging 1cba4dd7e611bb98d7539360d28a14995c9eddea into 62de467e231c2d41fc1eca1b13d9737b3dac66c8 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-5d20e984015ed80827129fad875e2c323a156b3b)

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 1 alert** when merging 704f5f7a781bac071a9f071ce320dfeb502195ce into 2cb131576419c25164147f0c3fd3df340a695a3e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-21b6b6585f155c1a269d14c393caf65870249492)

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 1 alert** when merging c13d449d0afb90b9ce446db7f7d221b9d1d5de78 into 156ac2f9461a82874a49ea05fb78c16b4eac9c0e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-66a460e361b77a8c926de81453a27659cac09ca3)

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 1 alert** when merging 63b818767bc289b05d812f640413a67573161da6 into 305084f9a156658e51e30aa9a53943e6c6ca22c5 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-485ad0d78255fa5a96dcc11b151b3489ca839cd4)

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 2 alerts** when merging 066b5c2a6483a425c6fbcc6e71006173b1808dc5 into 305084f9a156658e51e30aa9a53943e6c6ca22c5 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-dba19ed65146e5c4fd5128ef4c92b33219b58134)

**fixed alerts:**

* 2 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 2 alerts** when merging 09618dc447813f50ef283d2d828aa39366371eea into 263da3135543c4f0bf1061fd15be551ca541ac9a - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-09a0b1cc64856d1beb33020168a47a816e606189)

**fixed alerts:**

* 2 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 2 alerts** when merging 50a3607735693eaa8dca5c9607bf5413fceda406 into 4e95a2a2c74edf0380e35b5a792f5da9e6fe09cd - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-a9c1da4dab6ea5181522d69a1913be15677b6a68)

**fixed alerts:**

* 2 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 2 alerts** when merging b3aed23a4437de0145c252b3c1c7cea8cca27219 into 4e95a2a2c74edf0380e35b5a792f5da9e6fe09cd - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-a89a269a4a12bd158fc9c48e7a27ee83c82e6a52)

**fixed alerts:**

* 2 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging 3f838b861b6a425adb6a590807549be328b60b73 into 4e95a2a2c74edf0380e35b5a792f5da9e6fe09cd - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-16a4b269349275196a8ab6e249de44cff0097e2a)

**new alerts:**

* 1 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 1 alert** and **fixes 3** when merging bfff4fc5ec7ccbf9599b993804f9404fd2c5dbd9 into 4e95a2a2c74edf0380e35b5a792f5da9e6fe09cd - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-a4d9f824d3319edf68b27a6cb8b210bd08462386)

**new alerts:**

* 1 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 38c9ede22bc2e3c431b7cf85e0422674179e31eb into 8f148024430e0d2b2b7d31e43a4790a148619ded - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-c2e68e5016ab5f98d061bc0758a0cec417a1d725)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging cd07bb53da0df2e51c2ae28205411cc6a0d1d629 into f7f1910ef8e4ab7dbe89254a4f130cbcf01e1211 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-67df359679029f72ad7c27a2beeba70a306ef22e)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 215245e7809724d4a70ab986d5301e6c3471555a into f5ec98ecc47802d9c5b920d0b8e32074e1d3c1b9 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-00e2baff6ca0842ac89813a716bffa53c115d41a)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 4c63d029b2655a6c5cb7f3eb1482ac6b317c0819 into f5ec98ecc47802d9c5b920d0b8e32074e1d3c1b9 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-463e4d8d3f9a4e781c3f204660db21517232b879)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 89d6776e8f6a4cf90b394c31ed3f9a3d9860960a into 76d69ab60616d69ff43a13ff0c19b6ad42da93e7 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-3c43e9ff8588448f9b523e0d037d5d6c61412c1a)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 757cbfed31acd7c213117344d1ec15e0d119e46a into 506624e9a335635506dd9c3f4c647b83dc3d263e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-b621974f0f3fe104cd597441e1a7ef416ea0fe29)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging c27f843c1c5125c0ac7c455aba8b0654e8c3797f into 506624e9a335635506dd9c3f4c647b83dc3d263e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-b00ae355d125ac58b93ea9db7d0e69a3f5bed318)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging e68481f877bf2ffa39bdf751b3339342a113cde3 into 506624e9a335635506dd9c3f4c647b83dc3d263e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-ffa81b65b59bdaf67a588deb671cf1f1ea748bdb)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags
* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging f7983e0ab20dca3d688712637e0be6170fda2241 into 13013a70b7f9129436e008c63b6822dddba3ae09 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-c4c8ce486fc41d8fcfbab3046f7ec06c820b0e9c)

**new alerts:**

* 2 for Spurious Javadoc @param tags

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 4aac4e8469f237ee22e2c56196e7dd9aef43be75 into 13013a70b7f9129436e008c63b6822dddba3ae09 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-012eb343c8301a55daeeb421fe48b789754b3c03)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 2f427edcdb8020a902d5dc4daf83b9d3652ad1f9 into 13013a70b7f9129436e008c63b6822dddba3ae09 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-cc5b750c6235afabc27b219d31714f9ad2001f88)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 368ee390dc51dac1fae1b92a940b3600f405bdde into ec8c99e3a715b374b1cf332f1865bb7ad6ed87d5 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-13f4e0c8778a86977db7c32c22c8fcb3cf6e2543)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging eb21a3e12a169a02f93ee084378ee2e8f4825603 into e85288a3b9f726833e47442dd26f437c3c69e76a - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-7c396e59338f7f1ebcb6df2ee8e5ba270675a6d8)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 3c59bbcb31057e850998158f257fa52b2a0c3158 into e85288a3b9f726833e47442dd26f437c3c69e76a - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-ca68da113d805d84496a2fc670e3d96517c67a3a)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by puzzle-star** [comment]
I have tested the transacation-queue branch as it is today, and it is working fine for me. Still with some TOO_MANY_UNICAST errors as per my [comment in OH community](https://community.openhab.org/t/zigbee-binding/15763/2028?u=puzzle-star) (as expected), but even with these errors the whole system is working much better with the transaction manager than without it (and anyway these errors would be also happening, and much more indeed, without the transaction manager).

The main improvements I see in my network from this branch are:
- Before it, the dongle transmit queue grew uncontrollably under load (even if recovering afterwards)
- Without this, my Telegesys dongle was receiving many more concurrent transactions than it could handle under load (i.e. during network initialization) so most initialization commands were lost (with an error from the dongle) leading to having a certain amount of devices not properly configured or having to retry serveral times the discovery commands
- Prioritization: now transactions for sleepy devices do not fill the queue, improving latency for most "user" network commands (i.e. on/off, that normally go to non-sleepy devices)

Pedro

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 3d18ac95c7454f0ea83cd77da121262c9c6aced7 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-173cf7e1c2f5b6565715f429a61fd9b49cf2427e)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging edfe0f41df912b8bb0114d82f9532c30a1ad3a40 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-b26ac7f84b15d9ffd79fdcb71cc74f085ea7680d)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 4e612ddd3801d8007e65338282435225ab022063 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-c025f91aa5bf15cc73cdfeb9b40baf865e3e92a7)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 633b5662647996baa30ad472d03b9d0ebcd4775e into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-0516abfb32c3ec310ee12f610a5cc760c6f7985c)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging f0752856580438cfe695aeee01495052d66df6b4 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-584bc90c8bc2672b9745bc12e5d1a16f81f8965d)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 3dde623203533b9498fda44df6918c3e4510a6e0 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-7f36ccb5befe8fad62c892805ef704f66fac6f4f)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging ab60fa8a39179f86b3e9c40e01f099b801facd65 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-e2038ebb21575ee480243dbcb0ce767392e01932)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 1cbf13e6db0e283bc79fa8e4466fbb31a8bb1e38 into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-6992981a7f153a9dbbe4b663ddd4426e49c88912)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 9b36b4c6a484915c3d6f4260904a20ae5c8cf3af into 83a9d68b766b88a8bee7f036b47e8cd8168055b1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-60599f0329010359d88c84cd048a98748d8307e8)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging cfc975a83b8d780908b17f0e41ab5d5ada5f4f20 into 61560cf91349b106d55d0e2b168829983a25c5a9 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-454d3c5890d2e3d43c94b65a3573f498e2c3eee4)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging f7250ec70c48645c6b8b7619973b54fde4b3bb3e into 00aee52c9b88afc3a954f4ed1fb3c03f16dd0900 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-d149579df8b205bb0c3816e354097cceb60f120d)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging 218c2750553a65b382b41fb4401e83e47e7bf323 into 00aee52c9b88afc3a954f4ed1fb3c03f16dd0900 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-fe74b8f2bde09cfeb8258ccc8b4040c8c43df7e6)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **fixes 3 alerts** when merging f3e9b76fb18f9cf164c89c0bb2417fd54596af95 into 00aee52c9b88afc3a954f4ed1fb3c03f16dd0900 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-63f5c7e059da7f9f06f6c895900412d93112db54)

**fixed alerts:**

* 3 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
