### PR TITLE
WIP: Development of 1.2.0

### PR DESCRIPTION
**Pull request by cdjackson**
Opening this PR for visibility.

The ```dev-1.2.0``` branch will incorporate a number of (mostly minor) breaking changes. To avoid trickling these into the ```master``` branch, they are being merged into the ```dev-1.2.0``` branch at this time.

The ```dev-1.2.0``` branch will be contiually rebased against ```master```.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 5** when merging 70f05aa16728d39890f563002f8b196177df33b3 into 6bba704f605ea49273d6e2ceb13d1ab54294eaa1 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-2abe8e882e2e6c2ddab46df8d2255a846ea9c8f0)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Inconsistent synchronization of getter and setter
* 1 for Reference equality test of boxed types
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 4** when merging 65dbb3590cc6c397a3dca9bae249f625343c4488 into e9bca48b465e1aa45ca5b7b661a087395d42fcf9 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-acdbc6db71c15d2699621fb385550e25b40708be)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Inconsistent synchronization of getter and setter
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging 0ebb115d2d595870b692a004ae154429ba6b7931 into e9bca48b465e1aa45ca5b7b661a087395d42fcf9 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-63693f088364025c8fd4ee18b18f9133467469a0)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging 0586e932c26d3bcac836fb1a5fd62cd0ddb5f139 into 03bdd72f46762a7602f39ec81ac1a61c013bcf22 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-7b49bf0ecf59f752dbdc479c12e7bb57e8f85033)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging bb623c0ec351da75d6fd9c2aa6693dd93df54bdc into 1b18dee1642e42420b5b6ffe452874950462bc89 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-3982d05a9a0b5255bef85089a1252dd97538a3e5)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging 57a8a3e79c8921b3169b5dd03e7cd41aee0f5a7b into 1672f91cf30afbfa4edd6be1655f0ab478f3d428 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-b67badbf55e955c097fb2a31dea4c15117012f45)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging 93d19dab19f5655b0e8389fdf89d1c5c565d4d63 into 71f54513c00a2c242fb6cc0cac7ff72c0d5d53e5 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-f74f57f5fda59c0e900a835b5c2bfef08587d589)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging e925320c3fecdf8a59a86ae758b93af7c41bcbef into 6f2b803305a6c1e5e15cef9c7cdf85054e4ced6e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-43c9a3f9f1539f78accdd86a3b0ab3beb98798fb)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging cd88da15e0215eceb02e87e1b1cf998291818150 into 936da740dcdfa14b7d641202407eddb17c8f038c - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-41b472c142ed9f0a63b8dc9ae7b7690f08d8bb57)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging cfca6e7553cbc3b909ea312f47fc27ecaa846ebd into 476873d39f5b5857fbfcab4aab579564b899ecdf - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-9e6963d6a1474deebc90d01f902ab26146b7fd56)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging 1671d475f56f9b2ddc839ab36e35a324bda2d854 into 476873d39f5b5857fbfcab4aab579564b899ecdf - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-3d80faaf4aa5ea5a1d8cac1e665f501825f8d43f)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging edcce461b44da56de86e7d0f80a5e2b593b62013 into 476873d39f5b5857fbfcab4aab579564b899ecdf - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-9a8b8cbee5a42ecdc996e7f3a4a5fd152264aa5b)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 3** when merging f14fc5083965d87eef2786671781e257fdd2e0bc into a2699cd273f1ddf31c58930f4aca8f5d71ad5f62 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-50471b09f6ea45b88d4453246f549066b3294276)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 49047746d06147be7593978c117aba0eded902d5 into a2699cd273f1ddf31c58930f4aca8f5d71ad5f62 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-96239bc629061d36942b3e0bf507e7a6c8c45d9a)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 3611989e1f85748947e7fdc4bae6c4dfb21254c0 into a2699cd273f1ddf31c58930f4aca8f5d71ad5f62 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-b4223f44da6bb1a0d5461aba7b741023bd859224)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 339eef60cbc6b3b959ef985685bd61ce23542da8 into 9e8f8a36df959586c2a05120035ddc14cc90b2d0 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-0ae297691f91f5e40449a08857f90ebdc5c6fc4d)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 17a3a67d92ba31b32a9b1d380f30ddb6ba8dc07f into 8f10ab2bea8637a021b3e437848a58121196b69f - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-3a57268ec0c0b4da3bdf163a45d2c82bd35588d1)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 2ea048e2c009cfc0c81041af19e510352029e95d into 9fd5289e3be5cefb43a78292332282c548d6a99d - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-55e8ad80394e6005a5eef0c027418c2b52fda5d3)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging e584f4f2b697c6d0600cfe37ff387f3d5774a333 into 9fd5289e3be5cefb43a78292332282c548d6a99d - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-31e21e4b98bf3dbfb471e506683a4344cd14bde7)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 5402987ef12fbd6b26145f6c5825be80544c5a9c into 9fd5289e3be5cefb43a78292332282c548d6a99d - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-0751671ade2a02704376db89c0e4de81e476d62a)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 9dad42225f5ff5ee4d4ac7e642c8bb682216c872 into 9fd5289e3be5cefb43a78292332282c548d6a99d - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-824f07595b793546156845c2d7e6c41e7e9c071e)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging ff894db0b714efd4c5202d5cbfd6568f6afab2bb into fa372ea793ad4f3ec8b3733aa38b958003946287 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-477a53c99501b37b0412df869085acab133d6139)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging f293d84b0a9ff2e79e1d13988593f2642a0d0a0f into fa372ea793ad4f3ec8b3733aa38b958003946287 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-d64f62db85ce998ba4339ef545e4988acb008f3f)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging f054cf9ea0f924e47768d21dc322b01d0ed1f880 into fa372ea793ad4f3ec8b3733aa38b958003946287 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-cbf298d6ca036cc72d85bdf93971d54df9008676)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging e39ae9c2b272845cd7954fa11cfad142e39d7e58 into f86266f631c2600f39e7f57d066568af14b76b1a - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-653c6adc77fcebbb038552e0d4bb4cd191fd5d4f)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 2623c89d6a343647afe28ba9a0d30dcf0b8da17b into 671344622d6585e4cdde520c6756e343d5740209 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-1ee46347c7023ef63fb32178c9d9d8eded08774d)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 2eee72301c4282283d5420ab3aa54a79770a9c5c into 671344622d6585e4cdde520c6756e343d5740209 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-515b8f902477baf9f6bc252ed6c6be03be822e9c)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging 79634c259f8434965d31852aa1b0192789379def into be60958c99293311e4bf856c9137f938d0803dfb - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-7e35c0c51f4a47f322a5ac2d5c6480dd7e5dc15a)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by triller-telekom** [comment]
@cdjackson Any news on this branch? Is there something missing? Do you need help to resolve conflicts? @TomTravaglino  https://github.com/zsmartsystems/com.zsmartsystems.zigbee/issues/625#issuecomment-491206957 provided you the confirmation that his issue is properly addressed now in 1.2.

I saw you created another PR for 1.2:  https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/628

I agree that this is  a breaking change and thus should also go in 1.2. But IMHO we should focus to get 1.2 out of the door and then start collection breaking changes again for 1.3. instead of postponing 1.2 further and further. WDYT?

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging aae295caf0984c537065ddd5958b0847d8e317a1 into be60958c99293311e4bf856c9137f938d0803dfb - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-df4344db656d4ce3c5223da6393430260238571d)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 11** when merging b9c93a3aca1b81bf13d279b8edb68d025b909dd7 into be60958c99293311e4bf856c9137f938d0803dfb - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-dc566b95f00247145c96d9d6b830f920f3e22e5a)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 7 for Useless comparison test
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Useless null check
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
