### PR TITLE
Add ability to request NCP source route table

### PR DESCRIPTION
**Pull request by mikomarrache**

### CODE REVIEW

**Comment by mikomarrache** [comment]
I'm done with the changes on this branch. Let me know if you're okay with the changes. Thanks

**Comment by mikomarrache** [comment]
@cdjackson Hi, are you okay with the changes on this PR? Thanks!

**Comment by cdjackson** [comment]
Probably it's ok and sorry for forgetting about this. Let me take a look over the weekend - I had made a similar branch recently and I just wanted to check against my own version :)

**Comment by cdjackson** [comment]
@mikomarrache I've no major issue with this, but I've a few thoughts :)

I'm not sure if you looked at my branch - it's got a little more in it as instead of just printing out the source route table, the idea was to dump all routing information using a single console command rather than having to add multiple commands.

I didn't finish my updates (or maybe I finished it but didn't completely test - I forget as it was a few months back). I'd welcome your thoughts on the alternative approach.

**Comment by cdjackson** [comment]
Replaced by #1195

**Pull request closed without merging**
