### PR TITLE
Made OTA more robust by increasing retries and transfer timeouts

### PR DESCRIPTION
**Pull request by hanneshofmann**
This PR is intended to close https://github.com/zsmartsystems/com.zsmartsystems.zigbee/issues/450.

### CODE REVIEW

**Comment by cdjackson** [comment]
I must say that I'm very surprised that the timeout is now required to be 5 minutes and 20 retries are required to get the firmware version. This doesn't really sound right - it might solve your issue, but maybe this means there is a problem with the device? Or do you have another explanation as to why this is needed as you don't provide any information with the PR?

I'm not really happy to increase these defaults to this extent unless the protocol definition states that this is normal (it seems quite wrong to me) or there is a clear explanation. Maybe we should have a method to set these timeouts so it can be changed on a per device basis for your implementation.

**Comment by hanneshofmann** [comment]
First of all, thanks for your response and sorry for not providing any further information on this PR. This PR is intended to illustrate where we currently face issues regarding OTA. 

>This doesn't really sound right - it might solve your issue, but maybe this means there is a problem with the device? 

I completely agree with you that increasing the amount of retries and the timeout might solve individual device-specifics but is wrong in general.

>I'm not really happy to increase these defaults to this extent unless the protocol definition states that this is normal (it seems quite wrong to me) or there is a clear explanation.

Honestly, I don't know whether the protcol definition states that it is normal or not. I had observed that the current timeout of 30 seconds and the amount of 10 retries were not sufficient for almost every device* (except Osram bulbs :)).

> Maybe we should have a method to set these timeouts so it can be changed on a per device basis for your implementation.

That would work. As the transfer timeout is already configurable, we do only need to introduce a setter for the sleep time or the amount of retries to request the software version after the update - what do you prefer?


*I tested with several Bitron Video, Bitron Home, CentraLite and Osram devices including main- and battery-powered.

**Comment by cdjackson** [comment]
Sorry @hanneshofmann I missed the log you attached in the other issue.

I think for this issue, it is fine to increase ```TransferTimeoutPeriod``` - I think a longer default than the current 30 seconds is probably fine (the 5 minutes you propose in your PR seems reasonable). There is no timeout defined in the protocol docs (at least not that I can find). I guess that the device is taking time to verify the image has the correct checksum/hash/? before it sends the ```UpgradeEndCommand```.

The retries on the request for the version doesn't appear in the log you provided as the transfer doesn't complete. However, for the same reason as above, I think it's fair to extend the time here.

I suggest to update the retry time and max count to use a constant at the top of the file - if you want to provide setters, then feel free as well.

**Comment by hanneshofmann** [comment]
Thanks for your feedback, @cdjackson.

I also suppose that the current transfer timeout is not sufficient as the most ED might require more time to check the image integrity before they send the `UpgradeEndCommand`.

As suggested, I extracted the amount of retries and the sleep time as constants. Besides that, is there something else missing in the MR? I hope you don't mind that I've squashed and force pushed the latest changes.

**Comment by cdjackson** [comment]
Thanks - that looks fine to me.

**Pull request merged**
