### PR TITLE
Telegesis: Delay the start of the network state polling by 15 seconds

### LINKED ISSUE #640: Telegesis stick not working: Error setting Telegesis Prompt 1 register
By using the newest ZSS from the master branch (i.e. the merged 1.2 stuff) we noticed that a Telegesis stick is not working anymore.

It gets stuck on the call there it tries to set the "Prompt 1 register":

```
2019-05-22T16:42:39.496+0200   931  DEBUG          [symbolicName=org.openhab.binding.zigbee.telegesis, className=org.openhab.binding.zigbee.telegesis.handler.TelegesisHandler] - Initializing ZigBee Telegesis serial bridge handler.
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Initializing ZigBee network [zigbee:coordinator_telegesis:05001B8F].
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Channel 0
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - PANID XXX
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - EPANID XXX
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Network Key null
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Link Key null
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Config: zigbee_initialise found, initializeNetwork=false
2019-05-22T16:42:39.496+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Network Key String 
2019-05-22T16:42:39.536+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Network Key String has invalid format. Revert to default key.
2019-05-22T16:42:39.626+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Network key initialised 6352FBD0C1839B7AE418E39D8B23CDDD
2019-05-22T16:42:39.636+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Network key final array 6352FBD0C1839B7AE418E39D8B23CDDD
2019-05-22T16:42:39.636+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Link Key String 
2019-05-22T16:42:39.636+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Link Key String has invalid format. Revert to default key.
2019-05-22T16:42:39.666+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Link key final array 5A6967426565416C6C69616E63653039
2019-05-22T16:42:39.996+0200   931  DEBUG          [symbolicName=org.openhab.binding.zigbee.telegesis, className=org.openhab.binding.zigbee.telegesis.handler.TelegesisHandler] - ZigBee Telegesis Coordinator opening Port:'/dev/ttyUSB0' PAN:2a, EPAN:0000000000000042, Channel:0
2019-05-22T16:42:40.086+0200   148  DEBUG          [symbolicName=org.eclipse.smarthome.core, className=org.eclipse.smarthome.core.common.registry.AbstractManagedProvider] - Added new element zigbee:coordinator_telegesis:05001B8F to ManagedThingProvider.
2019-05-22T16:42:40.146+0200   154  DEBUG          [symbolicName=org.eclipse.smarthome.core.thing, className=org.eclipse.smarthome.core.thing.events.ThingStatusInfoEvent] - 'zigbee:coordinator_telegesis:05001B8F' updated: UNKNOWN
2019-05-22T16:42:40.156+0200   154  DEBUG          [symbolicName=org.eclipse.smarthome.core.thing, className=org.eclipse.smarthome.core.thing.events.ThingStatusInfoChangedEvent] - 'zigbee:coordinator_telegesis:05001B8F' changed from INITIALIZING to UNKNOWN
2019-05-22T16:42:41.086+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - ZigBee network starting
2019-05-22T16:42:41.086+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Initialising ZigBee coordinator
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.transaction.ZigBeeTransactionQueue] - Default: Set profile to ZigBeeTransactionProfile [maxOutstandingTransactions=2, interTransactionDelay=50, maxRetries=2]
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.transaction.ZigBeeTransactionQueue] - Broadcast: Set profile to ZigBeeTransactionProfile [maxOutstandingTransactions=3, interTransactionDelay=1200, maxRetries=0]
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.transaction.ZigBeeTransactionQueue] - Multicast: Set profile to ZigBeeTransactionProfile [maxOutstandingTransactions=3, interTransactionDelay=1200, maxRetries=0]
2019-05-22T16:42:41.086+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Mesh Update Period 86400
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNetworkManager] - Adding supported cluster 1280
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNode] - ClusterMatcher starting
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNode] - ClusterMatcher adding cluster 1280
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNetworkManager] - Adding supported cluster 25
2019-05-22T16:42:41.086+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNode] - ClusterMatcher adding cluster 25
2019-05-22T16:42:41.116+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.internal.ZigBeeNetworkStateSerializerImpl] - Loading ZigBee network state: Start.
2019-05-22T16:42:41.116+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.internal.ZigBeeNetworkStateSerializerImpl] - Loading ZigBee network state: File does not exist
2019-05-22T16:42:41.136+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNetworkManager] - Network state is updated to INITIALISING
2019-05-22T16:42:41.136+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - null: networkStateUpdated called with state=INITIALISING
2019-05-22T16:42:41.266+0200   930  DEBUG          [symbolicName=com.zsmartsystems.zigbee.dongle.telegesis, className=com.zsmartsystems.zigbee.dongle.telegesis.ZigBeeDongleTelegesis] - Telegesis dongle initialize.
2019-05-22T16:42:41.266+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeSerialPort] - Connecting to serial port [/dev/ttyUSB0] at 19200 baud, flow control FLOWCONTROL_OUT_NONE.
2019-05-22T16:42:41.306+0200   927  DEBUG          [symbolicName=org.openhab.binding.zigbee, className=org.openhab.binding.zigbee.handler.ZigBeeSerialPort] - Serial port [/dev/ttyUSB0] is initialized.


This is the error:

2019-05-22T16:44:02.276+0200   930  DEBUG          [symbolicName=com.zsmartsystems.zigbee.dongle.telegesis, className=com.zsmartsystems.zigbee.dongle.telegesis.ZigBeeDongleTelegesis] - Error setting Telegesis Prompt 1 register
2019-05-22T16:44:02.276+0200   930  ERROR          [symbolicName=com.zsmartsystems.zigbee.dongle.telegesis, className=com.zsmartsystems.zigbee.dongle.telegesis.ZigBeeDongleTelegesis] - Unable to configure Telegesis dongle
2019-05-22T16:44:02.286+0200   925  DEBUG          [symbolicName=com.zsmartsystems.zigbee, className=com.zsmartsystems.zigbee.ZigBeeNetworkManager] - Network state is updated to OFFLINE
```

I just tested the latest OH-2.5 snapshot with ZSS-1.1.6 and the stick works correctly.

@cdjackson  Any idea what could have gone wrong or where to start debugging?

### PR DESCRIPTION
**Pull request by triller-telekom**
Fixes #640

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by cdjackson** [comment]
Do you think this is the best approach? With other drivers, we do not poll when the network is down to prevent any interference with the initialisation process. I think that might be a better option to solve this issue?

**Comment by triller-telekom** [comment]
No I don't know whether it is the best approach. I think that sending out those network information packets only when we are online would be better.

However, I currently see no easy way to get the network state from within the `TelegesisFrameHandler`.

Since you know the code better than I do, maybe you can have a look, please?

**Comment by cdjackson** [comment]
I'll take a look. I think in the other handlers it doesn't use "network state" - it uses "transport state" - which for this purpose is I think pretty much the same. I think the Ember driver just uses a flag when the network is up so I'll implement something similar.

**Comment by triller-telekom** [comment]
Closing in favor to #647.

**Pull request closed without merging**
