### PR TITLE
Network state transition update

### PR DESCRIPTION
**Pull request by cdjackson**
Update ```ZigBeeNetworkState``` transitions as per #583 discussion.

Adds a ```reinitialize``` method to ```ZigBeeNetworkManager``` to take the network offline and allow reconfiguration.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
@triller-telekom this is updated with the ```reinitialize``` method - are you able to easily test to see if it resolves your issue before I merge?

**Comment by triller-telekom** [comment]
I can probably give it a try tomorrow

**Comment by triller-telekom** [comment]
One question though:

```
    public ZigBeeStatus reinitialize() {
        // Set the state to INITIALISING before reconfiguring the transport layer
        // to ensure we don't pass the OFFLINE state to the application
        setNetworkState(ZigBeeNetworkState.INITIALISING);

         return ZigBeeStatus.SUCCESS;
    }
```

This seems to only set the state to INITIALISING. Does that mean that my application has to call `reinitialize()` first and then `startup(true)` to make the network manager write the new configuration values onto the chip?

I thought your `reinitialize()` method would take care of that internally.

Or did you do it to have it consistent with `initialize()` +`startup()`, where also both methods have to be called by the application?

**Comment by cdjackson** [comment]
Yes - the reinitialise method is to put the state back into INITIALIZE - so the same state as if you had called the initialise() method. It doesn’t actually initialise anything, but as some methods can only be called between initialise and startup, you need to put the system back into INITIALIZE state, update the configuration, then call startup().

There is still a potential issue with this, and that is that there’s currently no way to take the transport OFFLINE which may also be needed in some instances. This requires a further update to the transport interface.

**Comment by triller-telekom** [comment]
I can confirm that it works.

I have re-configured the network via

```
networkManager.setZigBeePanId(Integer.parseInt(panID));
networkManager.setZigBeeExtendedPanId(new ExtendedPanId(extendedPanID));
networkManager.setZigBeeChannel(ZigBeeChannel.create(Integer.parseInt(channel)));
networkManager.setZigBeeLinkKey(new ZigBeeKey(linkKey));

ZigBeeKey key = new ZigBeeKey(networkKey);
key.setOutgoingFrameCounter(frameCounter);
networkManager.setZigBeeNetworkKey(key);
```
and then did this:

```
networkManager.reinitialize();
networkManager.startup(true);
```

Afterwards the network is back working fine. Also the `ZigbeeNetworkState` does **NOT** go to OFFLINE in-between, which is what we want.

**Comment by cdjackson** [comment]
Thanks for testing @triller-telekom

**Pull request merged**
