### PR TITLE
Fix for race condition in ZclCluster::notifyCommandListener per  #773

### PR DESCRIPTION
**Pull request by sesuncedu**
Fix for immediate issue in #773
Fix race condition causing incorrect value to be returned in ```ZclCluster::notifyCommandListener```, wherein the latch count was decremented before the response was set.

In the event of a timeout or interrupted exception, the current value of the response is used. This will give the correct result (possibly after a timeout) if the size of the listener set is reduced after the latch has been created, but before the loop has started. 

This PR does not fix other preexisting concurrency issues such as those involving multiple listeners which may return true. 

The 

Signed-off-by: Simon Spero <sesuncedu@gmail.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks. Please can you run the formatter on this and I'll take a look.

What do you mean by -:

> This PR does not fix other preexisting concurrency issues such as those involving multiple listeners which may return true.

I don't think there is any concurrency issue if multiple listeners return true. If ANY listener returns true then this will exit. There should not be any concurrency problem with this - or am I missing something.

**Comment by sesuncedu** [comment]
> Thanks. Please can you run the formatter on this and I'll take a look.

Can you let me know what is not being formatted correctly?  I imported the eclipse formatter settings and   "ESH" is active.  Is something not getting imported correctly? 

> > This PR does not fix other preexisting concurrency issues such as those involving multiple listeners which may return true.
> 
> I don't think there is any concurrency issue if multiple listeners return true. If ANY listener returns true then this will exit. There should not be any concurrency problem with this - or am I missing something.

The issues I fixed do address the race cases.  

The concurrency concern referred to is indeed the overall one of multiple listeners sending responses to a command, which I was deeming to be outside the scope of this pull request, since that may be intended behavior. 

I feel a bit icky relying on timeouts to give correct behavior if a listener is removed at an awkward time, but I would also feel icky making a defensive copy of a copy on write set. It's correct, and faster in all but the edge case. 

The timeout was already there  when I got here, occifer.

**Comment by cdjackson** [comment]
> Can you let me know what is not being formatted correctly?

There are a few things - for starters take a look at the if/else statements - the spacing is not correct so it tells me the code is not formatted.

> The issues I fixed do address the race cases.

Sure - I didn't insinuate that it didn't. My point was just that multiple listeners reporting true is in itself not an issue. I know it results in the potential for multiple responses, which I agree isn't nice, but it's not easy to resolve this. Probably there should not be multiple listeners responding to a message or there is likely another issue in the application.

> The concurrency concern referred to is indeed the overall one of multiple listeners sending responses to a command,

Ok, I don't really think that's a concurrency issue, but understood.

> I feel a bit icky relying on timeouts to give correct behavior if a listener is removed at an awkward time

The listeners should in theory be protected, but I'd not considered what happens if a listener is removed while it's waiting. Maybe there's something else needed if that's the case as I agree that's not so nice. If you have a suggestion to resolve this, then please suggest away :)

**Comment by sesuncedu** [comment]
The formatter was not being auto-applied, but also had some stuff not imported 
(import blocks and annotation blank lines).  

 I usually reflexively hit reformat even when I shouldn't, and so I was looking for spurious diffs.

**Comment by cdjackson** [comment]
Perfect - thanks. I’ll take a look at this tomorrow (it’s getting late here now :) ).

**Pull request merged**
