### PR TITLE
fix compilation issue introduced in PR #1041

### PR DESCRIPTION
**Pull request by mikomarrache**

### CODE REVIEW

**Comment by cdjackson** [comment]
Have you had to manually make these changes? If so we probably should address the autocoder to fix this otherwise these changes will be automatically reverted.

**Comment by mikomarrache** [comment]
Ok - I think I got it. I missed the auto_size element.

Is that ok?

**Comment by cdjackson** [comment]
There is something still failing with this - I'll merge this since it looks ok and will sort out any subsequent issues.

**Comment by cdjackson** [comment]
Not sure why the CI seemed to fail - it's compiling fine locally here.

**Comment by mikomarrache** [comment]
I guess the CI failed because this PR doesn't compile on its own. It depends on the other one (#1041).

**Comment by cdjackson** [comment]
But wasn’t that already merged? I’m pretty sure I merged, that, then you provided the fix for the compilation problem…

Anyway, it seems to be compiling now, and certainly worked ok locally here.

Thanks.

**Pull request merged**
