### PR TITLE
Set extended timeouts for EZSP unicast messages.

### PR DESCRIPTION
**Pull request by sesuncedu**
Provide a ZigBeeNetworkManager.
If node information is available for a unicast destination, the ieee address is known, and the destination is known to be RX_OFF , set extended timeout.

The timeout flag is set for every outgoing message. 

An alternative approach would have been to maintain address table entries and send via the address table.

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks @sesuncedu.

I think I've mentioned this elsewhere, but I'm not super keen on providing access to the ```ZigBeeNetworkManager``` from the transport layer. I think this is open to "abuse" and is not really nice architecturally to provide such high level access to the lower layers (IMHO ;) ).

I also don't like the fact that this is configured on every command, but maybe that's necessary? I would have preferred that it is set once when required (eg when we first work out that the device is an ZED) and not on every frame as I don't think that is necessary from the NCP perspective (although I've not looked at this command in a long while, so I could be wrong?).

We already have problems with too many commands being sent through the SPI handler, and this will increase the number of frames sent for each command, thus compounding the problem.

My preference would be to add a method (or methods) to the ```ZigBeeTransportTransmit ``` interface to set this sort of thing and make the ```ZigBeeNetworkManager``` responsible for explicitly setting them.

What do you think?

Also, why do you need to disable animal sniffer on the autocoder? I've not noticed any issues with this, although it would probably be better in a separate PR to keep the issues clean.

Thanks.

**Comment by sesuncedu** [comment]
Animal sniffer was  about java.nio stuff in the autocoder. It's stopped for now. I have no idea why.

**Comment by sesuncedu** [comment]
These changes seems to be surfacing some issues with transaction queues, so it is on hold while I try to figure out what the issue is.

**Comment by cdjackson** [comment]
Ok, thanks. Just reach out if you want to discuss anything - I'm happy to try and help.

What timezone are you in by the way?

**Comment by sesuncedu** [comment]
I'm geographically on  EDT

**Comment by sesuncedu** [comment]
A related issue  shows up is a side effect of the behavior of the openhab zigbee IAS Zone converter, which generates multiple default responses for each zone status notification or reported change. 

These responses are generated in a burst, and with extended timeouts and the current transaction queuing discipline, these can accumulate. 

If there are a large number of transactions to a Sleepy ED on a queue, no other sources of traffic,  and the  number of outstanding transactions is limited,  then outgoing messages will only be sent when an incoming message arrives to free up a slot.  

Assuming that the end-to-end transfer time is small relative to the sleepy devices polling interval, it is quite likely that by the time the incoming message has been delivered up to the application level the sleepy device will have finished polling and turned off its receiver, requiring the next message to also wait   for more or less a complete  polling period to be delivered. 

Each unacknowledged message requires a buffer on the NCP, and these are relatively scarce.  The ideal approach would be to estimate when a device will next poll, and release one or more  messages addressed to the device so that they will be delivered to the parent shortly before the device will poll.  A reasonable estimator  should be able to reduce the time that the outgoing message spends occupying an aps-ack-wait slot on the ncp and an indirect buffer on the end device's parent.

**Comment by sesuncedu** [comment]
This is an illustrative sequence. 

The time to the next completion when no transaction intervenes is fairly consistent - just over 7 seconds. 
The time to the next completion after a message is added to the queue (which probably means there was an incoming message) is much shorter - ~1/4 second. This is consistent with the device being in fast-poll mode after the sending the outgoing message. 

```
2019-10-15 14:50:04.183 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=38, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=66, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:50:04.193 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:04.682 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:07.336 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=37, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=67, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:50:07.621 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:07.891 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:14.916 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:22.029 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:22.101 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=34, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=68, commandIdentifier=0, statusCode=SUCCESS]]
2019-10-15 14:50:22.121 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=35, transaction=ZigBeeTransaction [queueTime=1, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=68, commandIdentifier=0, statusCode=SUCCESS]]
2019-10-15 14:50:22.124 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=36, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=68, commandIdentifier=0, statusCode=SUCCESS]]
2019-10-15 14:50:22.135 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=37, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=68, commandIdentifier=0, statusCode=SUCCESS]]
2019-10-15 14:50:22.291 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=38, transaction=ZigBeeTransaction [queueTime=1, state=WAITING, sendCnt=0, command=DefaultResponse [IAS Zone: 0/0 -> 21096/1, cluster=0500, TID=69, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:50:22.303 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:29.410 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:36.427 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:43.482 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:50.559 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:50:57.618 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:04.693 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:11.738 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:13.443 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=31, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=6A, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:51:13.715 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:13.973 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:14.490 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:21.535 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:28.607 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:35.675 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:42.737 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:49.816 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:51:57.156 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:04.556 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:11.559 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:18.638 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:19.525 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=20, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=6B, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:52:19.791 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:26.884 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:33.960 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:41.273 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:48.334 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:52:55.391 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:02.472 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:09.527 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:16.608 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:23.687 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:25.637 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=11, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=6C, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:53:25.886 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:32.962 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:40.037 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:47.102 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:53:54.165 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:01.212 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:08.284 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:15.342 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:22.407 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:29.475 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:31.737 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=2, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=6D, commandIdentifier=10, statusCode=SUCCESS]]
2019-10-15 14:54:31.988 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:39.185 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:54:46.150 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: transactionComplete COMPLETE 0
2019-10-15 14:55:37.832 [DEBUG] [e.transaction.ZigBeeTransactionQueue] - 286D9700010168AE: Added transaction to queue, len=1, transaction=ZigBeeTransaction [queueTime=0, state=WAITING, sendCnt=0, command=DefaultResponse [Temperature Measurement: 0/0 -> 21096/1, cluster=0402, TID=6E, commandIdentifier=10, statusCode=SUCCESS]]
```

**Comment by sesuncedu** [comment]
I would really like to get something merged in to the mainline code soon. 
This PR is not the one I would submit, since it has drifted from the branch I work on. 

The level 4 transport  needs access to the collection of information about the Level 3  nodes that is held by the ZigbeeNetworkManager class; in particular, the information about the Level 2 Mac capabilities that are made available via   Node Descriptor Discovery / the Device Announce command.

Would you be ok if I extracted an interface with  and used that in the method api, even though it would just  be passing in the ZigbeeNetworkManager instance? This is  being done for the RX side of command processing.

**Comment by cdjackson** [comment]
I'm not happy to pass the network manager to the transport layer (I've said this as part of a review somewhere else I think. I'm potentially happy to add an interface to allow the transport to request targetted information, or probably my preference would be for the network manager to explicitly set the information in the transport.

Before doing this, I would like to close out the questions about the Ember "race condition" - you raised an issue, and I reviewed a PR that you have closed without comment and you've not responded to any of my questions on this. That was a simple PR so it would be good to get it closed before we more on opening up more issues.

**Comment by cdjackson** [comment]
This feature has been added elsewhere so closing this as there has been no response for over 2 months.

**Pull request closed without merging**
