### PR TITLE
Deprecate cluster commands

### PR DESCRIPTION
**Pull request by cdjackson**
This migrates the API away from using the cluster methods to send commands, and instead to send a command via the ```cluster.sendCommand()``` method, but instantiating the command separately. This is primarily designed to allow the command to be manipulated prior to sending which is not currently possible at all. For example, disabling default response can now be configured on the command before sending.

This also deprecates the setters in the commands in favour of a new constructor that takes all mandatory fields, thus ensuring that parameters cannot be missed.

Eg -:

the following...

```
leveControlCluster.moveToLevelCommand(level, time)
```

becomes...

```
leveControlCluster.sendCommand(new MoveToLevelCommand(level, time));
```

or...

```
MoveToLevelCommand command = new MoveToLevelCommand(level, time); 
command.setDefaultResponse(false);
leveControlCluster.sendCommand(command);
```

Note that this does introduce a lot of deprecation warnings within the framework which I will look at in subsequent PRs (first up is to fix the initial problem with disabling the default response in the OTA server).

@wsowa would appreciate you taking a quick look at this if you have a few minutes.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpPairingConfiguration.java  3
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/UpgradeEndCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/BackupBindTableResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/RecoverSourceBindRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/levelcontrol/MoveCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementDirectJoinResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImageBlockResponse.java  2
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpPairing.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImageBlockCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/QuerySpecificFileResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementRoutingRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ReplaceDeviceResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpNotification.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementLeaveResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpProxyTableRequest.java  2
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/StoreBackupBindEntryResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/MoveSaturationCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/MoveHueCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImagePageCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpCommissioningNotification.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementBindRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementLqiRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/EndDeviceBindResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/QueryNextImageResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/levelcontrol/MoveWithOnOffCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/EnhancedMoveHueCommand.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/zsmartsystems/com-zsmartsystems-zigbee/pullRequest?prid=4804464&bid=15986010)

**Comment by wsowa** [comment]
Hi. Looks good to me. Only one thing I have noticed is that commands that have no arguments have their only constructor deprecated now. See ClearWeeklySchedule class for example. Not sure if you want to deal with it now or later when resolving all the deprecated warnings. Other than that looks good.

**Comment by cdjackson** [comment]
Thanks @wsowa - I'd not noticed this. Previously there was no constructor in these classes, but I had to add the default constructor for compatibility when I added the parameterised constructor. I marked this as deprecated, but will change this for commands with no parameters.

**Comment by cdjackson** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImageBlockCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpPairingConfiguration.java  3
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/levelcontrol/MoveWithOnOffCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/MoveSaturationCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImagePageCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/QueryNextImageResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/levelcontrol/MoveCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpPairing.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpProxyTableRequest.java  2
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/MoveHueCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpCommissioningNotification.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ReplaceDeviceResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/colorcontrol/EnhancedMoveHueCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/ImageBlockResponse.java  2
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/UpgradeEndCommand.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementBindRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementRoutingRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementLeaveResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/greenpower/GpNotification.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementLqiRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/BackupBindTableResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/EndDeviceBindResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zcl/clusters/otaupgrade/QuerySpecificFileResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/StoreBackupBindEntryResponse.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/RecoverSourceBindRequest.java  1
- com.zsmartsystems.zigbee/src/main/java/com/zsmartsystems/zigbee/zdo/command/ManagementDirectJoinResponse.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/zsmartsystems/com-zsmartsystems-zigbee/pullRequest?prid=4804464&bid=15986010)

**Pull request merged**
