### PR TITLE
Add new Data Store serialisation concept

### LINKED ISSUE #513: Refactoring of the network serialisation interface
The current network serialisation has a couple of problems that need to be resolved.

1) On large networks or slow computers, serialisation of the network can be slow - ie it can take 5 seconds or more to serialise the whole network. We see this taking 5 seconds with an RPi, and 40 nodes on openHAB.
2) If there are a lot of updates, these get queued due to the thread synchronisation which further slows things down. There possibly should be some level of delay to ensure that only the last update is persisted.

I propose to change the network serialisation to deprecate the current interface, and either add a new interface, or to require implementors to implement their own solution using the ```ZigBeeNetworkNodeListener``` which is called when nodes are added and removed.

I think given the high dependency the framework has on this serialisation, that a specific interface is useful rather than using the ```ZigBeeNetworkNodeListener``` interface, but welcome any thoughts.

@hsudbrock @puzzle-star FYI if you have any comments.

### PR DESCRIPTION
**Pull request by cdjackson**
This refactors the serialisation interface. It adds a new ```ZigBeeNetworkDataStore``` interface that is used to read/write/remove nodes. Users should implement this interface as they see appropriate for their system (eg SQL database, XML files, Json...).

This is different to the current serialisation interface which acts on the whole network. This causes problems with slower computers (eg RPi class) and larger networks where this can take in the order or 1 to 3 seconds to serialise. Additionally, multiple serialisations may occur at once (or close together) and this can cause blocking of the system for significant periods of time.

This implementation includes a ```ZigBeeDatabaseManager``` that manages the data store. It listens to the node update notifications, and will update the data store. The manager will defer writes for a short time to avoid multiple updates. This time is set to 250ms by default. If updates continue to be received for a device, then the manager will still store periodically (ie the hold-off will not act indefinitely in the case where many updates are received). This maximum period is set to 1 second by default.

Closes #513 
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
@puzzle-star did you test this further at all in the OH binding?

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging 4682aa900f774def323fad8d78be636f86df80f0 into cf0631cfeb44a23aa1f94974af40214db3d5d7d2 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-5b8f45f2d9b5cc137c07615c35bc2ce200f6395f)

**new alerts:**

* 1 for Result of multiplication cast to wider type
* 1 for Potential output resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by puzzle-star** [comment]
Hi @cdjackson,

Welcome back!

I did not manage to make Maven point to the development libraries I compiled with the forked branch to compile the binding.

I have zero experience with Maven/Tycho and maybe this should be an easy thing to achieve, but I struggled for a whole day and gave up.

If this is something you can easily point me in the right direction, happy to do it. If not, I cannot till there is a snapshot version of the ZSS with the changes on the repo...

**Comment by cdjackson** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging 4fed6fc6539102743d8a11352a876f5ded3f2763 into 62de467e231c2d41fc1eca1b13d9737b3dac66c8 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-ef564fcd14c96c202516e92ae0266a96322fb4cd)

**new alerts:**

* 1 for Potential output resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 1 alert** and **fixes 2** when merging f9ef351d88737ba85ce7847f32093dc6156e87ef into 62de467e231c2d41fc1eca1b13d9737b3dac66c8 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-5655f82239ded8595ba8bf5cda01e022aaded1c5)

**new alerts:**

* 1 for Potential output resource leak

**fixed alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 7** when merging a6382930c746f24908631186e87faf655d58783d into 62de467e231c2d41fc1eca1b13d9737b3dac66c8 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-85b397ce5de4b6245b0bd13d2d618ef8e10bb9c3)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 2 for Missing format argument
* 1 for Result of multiplication cast to wider type
* 1 for Inconsistent synchronization of getter and setter
* 1 for Reference equality test of boxed types
* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
Hi @puzzle-star. For debugging I normally do this in the Eclipse IDE where it is a simple matter to add the new JARs into the running TP. I think you are not using the IDE though (??) so I'm not 100% sure how to do this directly in Maven). I can talk you through doing it in the IDE if you want?

**Comment by puzzle-star** [comment]
Hi @cdjackson,

Let me try if I manage to make maven "behave". If not, I will manually compile the jar as I used to do before using maven.


Best Regards,
Pedro

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 7** when merging 932a279a2575b6fbfc1b25c24712caa485afd718 into da475facf3c569a07db132d6d781609498b1b1ae - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-8ebc00500ed403140301267d6d1dd3dee231f587)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 2 for Missing format argument
* 1 for Result of multiplication cast to wider type
* 1 for Inconsistent synchronization of getter and setter
* 1 for Reference equality test of boxed types
* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 7** when merging e58b537511bbe115a81b08447347d40babe2e161 into 156ac2f9461a82874a49ea05fb78c16b4eac9c0e - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-1990a635507de20ab79f1ede646b6a9a203aa38a)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 2 for Missing format argument
* 1 for Result of multiplication cast to wider type
* 1 for Inconsistent synchronization of getter and setter
* 1 for Reference equality test of boxed types
* 1 for Potential output resource leak
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by t-8ch** [comment]
The `ZigBeeDataStore` seems to leak devices that are removed while the datastore is not running.
The previous one-file implementation would purge these devices during the next serialization.
The new implementation will never have `removeNode()` called and will keep returning the removed device from `readNetworkNodes()` and `readNode()`.

Not sure if this is an issue and/or if it should be mitigated by the library or implementors of `ZigBeeNetworkDataStore`

**Comment by cdjackson** [comment]
I guess that the system only knows that a device is removed, if it is removed by the application, so the application should remove any unknown nodes.

Currently I don’t know of an easy way to know if a node has REALLY left the network - there is no centralised repository of this information, so it’s only possible to know this by the application. If you are removing devices, then you should remove them from the network.

**Comment by cdjackson** [comment]
> The previous one-file implementation would purge these devices during the next serialization.

Actually this is incorrect. The node would only be removed at the next serialisation if it was removed from the NetworkManager, so this will be the same as the new system. Otherwise, the single file system reads all the nodes in from the file, creates the ZigBeeNodes, and when the state is serialised, the same nodes will be serialised out.

**Comment by cdjackson** [comment]
This pull request **introduces 2 alerts** and **fixes 5** when merging 2ca42594821dcba02d2990b911758a4428188c99 into 22a1bbc61ccd4b2972294b6cc4b0cda3a0803151 - [view on LGTM.com](https://lgtm.com/projects/g/zsmartsystems/com.zsmartsystems.zigbee/rev/pr-a8c739689414f6219c117f52ff1987a9abe4eaf4)

**new alerts:**

* 1 for Potential output resource leak
* 1 for Potential input resource leak

**fixed alerts:**

* 1 for Inconsistent synchronization of getter and setter
* 1 for Reference equality test of boxed types
* 1 for Potential output resource leak
* 1 for Missing format argument
* 1 for Potential input resource leak

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
