### PR TITLE
Updates to fix issues with sending ezsp frames.

### PR DESCRIPTION
**Pull request by cschwer**
Added check that timerTask is running.
add reset for retries counter
drop message if retry count is exceeded
wrap sendRetry in try/catch so that retry timer does not get killed.

Signed-off-by: Charles Schwer charles.schwer@gmail.com

### CODE REVIEW

**Comment by cdjackson** [comment]
I've added a CLA to the project - just to protect everyone so say that any contributions can be  used without copywite issues. It should be reasonably simple to click on the button that you hopefully see (assuming you agree of course ;) ).

**Comment by cschwer** [comment]
Yep, I saw the CLA and figured as much.  I have signed it already, hopefully I did that right.

**Comment by cdjackson** [comment]
I think this looks fine and clearly you're using the Ember interface more than me at the moment. Can I just get you to add a signed-off-by signature to the PR please.

**Comment by cschwer** [comment]
yep, added signature to original comment.

**Pull request merged**
